### ISSUE TITLE
 no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::Value>)’

### ISSUE THREAD

**Issue by benerd** [Webini/node-gstreamer-tools#1]
Not able to install using npm, here is the complete error stack.

node-gstreamer-tools@1.1.1 install /opt/server/node_modules/node-gstreamer-tools
> node-gyp rebuild

make: Entering directory '/opt/server/node_modules/node-gstreamer-tools/build'
  CXX(target) Release/obj.target/gst-discover/src/GLibHelpers.o
../src/GLibHelpers.cpp: In function ‘v8::Local<v8::Value> gintrange_to_v8(const GValue*)’:
../src/GLibHelpers.cpp:63:90: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::IntegerFactory<v8::Int32>::return_t)’
   63 |   object->Set(Nan::New("min").ToLocalChecked(), Nan::New(gst_value_get_int_range_min(gv)));
      |                                                                                          ^
In file included from /home/ubuntu/.cache/node-gyp/14.16.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../src/GLibHelpers.cpp:2:
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
../src/GLibHelpers.cpp:64:90: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::IntegerFactory<v8::Int32>::return_t)’
   64 |   object->Set(Nan::New("max").ToLocalChecked(), Nan::New(gst_value_get_int_range_max(gv)));
      |                                                                                          ^
In file included from /home/ubuntu/.cache/node-gyp/14.16.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../src/GLibHelpers.cpp:2:
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
../src/GLibHelpers.cpp: In function ‘v8::Local<v8::Value> gintfraction_range_to_v8(const GValue*)’:
../src/GLibHelpers.cpp:70:99: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::Value>)’
   70 |   object->Set(Nan::New("min").ToLocalChecked(), gvalue_to_v8(gst_value_get_fraction_range_min(gv)));
      |                                                                                                   ^
In file included from /home/ubuntu/.cache/node-gyp/14.16.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../src/GLibHelpers.cpp:2:
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
../src/GLibHelpers.cpp:71:99: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::Value>)’
   71 |   object->Set(Nan::New("max").ToLocalChecked(), gvalue_to_v8(gst_value_get_fraction_range_min(gv)));
      |                                                                                                   ^
In file included from /home/ubuntu/.cache/node-gyp/14.16.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../src/GLibHelpers.cpp:2:
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
../src/GLibHelpers.cpp: In function ‘v8::Local<v8::Value> gfraction_to_v8(const GValue*)’:
../src/GLibHelpers.cpp:77:95: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::IntegerFactory<v8::Int32>::return_t)’
   77 |   object->Set(Nan::New("num").ToLocalChecked(), Nan::New(gst_value_get_fraction_numerator(gv)));
      |                                                                                               ^
In file included from /home/ubuntu/.cache/node-gyp/14.16.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../src/GLibHelpers.cpp:2:
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
../src/GLibHelpers.cpp:78:99: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::IntegerFactory<v8::Int32>::return_t)’
   78 |   object->Set(Nan::New("denom").ToLocalChecked(), Nan::New(gst_value_get_fraction_denominator(gv)));
      |                                                                                                   ^
In file included from /home/ubuntu/.cache/node-gyp/14.16.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../src/GLibHelpers.cpp:2:
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
../src/GLibHelpers.cpp: In function ‘void gst_tags_to_v8_iterate(const GstTagList*, const gchar*, gpointer)’:
../src/GLibHelpers.cpp:191:20: warning: missing initializer for member ‘_GValue::data’ [-Wmissing-field-initializers]
  191 |   GValue val = { 0 };
      |                    ^
../src/GLibHelpers.cpp:200:3: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::Value>)’
  200 |   );
      |   ^
In file included from /home/ubuntu/.cache/node-gyp/14.16.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../src/GLibHelpers.cpp:2:
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
../src/GLibHelpers.cpp: In function ‘gboolean gst_structure_to_v8_value_iterate(GQuark, const GValue*, gpointer)’:
../src/GLibHelpers.cpp:211:3: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::Value>)’
  211 |   );
      |   ^
In file included from /home/ubuntu/.cache/node-gyp/14.16.0/include/node/node.h:67,
                 from ../../nan/nan.h:56,
                 from ../src/GLibHelpers.cpp:2:
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/ubuntu/.cache/node-gyp/14.16.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
make: *** [gst-discover.target.mk:123: Release/obj.target/gst-discover/src/GLibHelpers.o] Error 1
make: Leaving directory '/opt/server/node_modules/node-gstreamer-tools/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.4.0-1038-aws
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v14.16.0/bin/node" "/home/ubuntu/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/server/node_modules/node-gstreamer-tools
gyp ERR! node -v v14.16.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN server@1.0.0 No description
npm WARN server@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-gstreamer-tools@1.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-gstreamer-tools@1.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-03-18T06_05_36_499Z-debug.log

**Comment by Webini** [comment]
Hi, node 14 wasn't compatible with this package.
It should now be resolved in version 1.1.2
